### ISSUE TITLE
json obj data invalid

### ISSUE THREAD

**Issue by kart-able** [vinodsr/node-red-contrib-tuya-smart-device#31]
Hello,

The ID and key seem to be correct as the node displays "connected" underneath.

But **I did not send anything through it**, debug already says "json obj data invalid" with a msg: Object listing dps 1, 2, 3, 101, 102, 103 as null.

**Comment by vinodsr** [comment]
Make sure you understand the schema of the device. 

The easiest way to do that is to attach a debug node to the smart node and  interact with the device .. 

eg: Try turning on and off the device, you will see the payload in the debug panel. Send that payload to the node and device will turn off or on . 


If this is not working then it can be due to this one https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/14 (some devices are infected.)
