### ISSUE TITLE
Light bulb color control

### ISSUE THREAD

**Issue by xjustbmw** [vinodsr/node-red-contrib-tuya-smart-device#59]
I managed to start up the bulb using localkey and dps changed to 20 based on the flow1.js example

are there any examples to change to white/color, and select color for the bulb?
See documentation link is only stated in a picture.

thanks

**Comment by xjustbmw** [comment]
i figured it out by debugging the output of the light and sending commands from smart life app :)

is there any way to listen the output of devices that are usually offline and connect only when an event is present ?
 like water leak detectors, motion sensors, etc ?

**Comment by msillano** [comment]
>  is there any way to listen the output of devices that are usually offline and connect only when an event is present ?


[tuyaDAEMON](https://github.com/msillano/tuyaDAEMON) solves the problem using tuya-cloud and a 'brige': see [TRIGGER topic](https://github.com/msillano/tuyaDAEMON/tree/main/ tuyaTRIGGER) and see also the [minimum flow] (https://github.com/msillano/tuyaDAEMON/tree/main/extra/tuyaTRIGGER%20for%20node-red%20users) to get it working.

The trick requires a 'smart switch' that acts as a "brige", but, since only the "countdown" function is used, the switch is still available for any purpose.

Best regards.
m. s.
